// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "Arduino_secrets.h"
const char DEVICE_LOGIN_NAME[]  = "1f01866f-bed5-4345-a5c3-d4d16f866cd2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGasRatioChange();
void onHumidityChange();
void onTempratureChange();
void onFireAlertChange();
void onFlameDetectedChange();

float gas_ratio;
float humidity;
float temprature;
bool fire_alert;
bool flame_detected;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gas_ratio, READWRITE, ON_CHANGE, onGasRatioChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(temprature, READWRITE, ON_CHANGE, onTempratureChange);
  ArduinoCloud.addProperty(fire_alert, READWRITE, ON_CHANGE, onFireAlertChange);
  ArduinoCloud.addProperty(flame_detected, READWRITE, ON_CHANGE, onFlameDetectedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);